{{- if .Values.onPremToken }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: central-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: central-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: central-ui
    spec:
      containers:
        - name: central-ui
          {{ $imageTag := .Values.image.tag | default .Chart.AppVersion }}
          image: {{ template "utils.imageName" (dict "Values" .Values "Component" "central-ui" "Tag" $imageTag) }}
          env:
          - name: NEXT_PUBLIC_BACKEND_URL
            value: "http://central-backend.{{ .Release.Namespace }}.svc.cluster.local:8081/graphql"
          - name: NEXT_PUBLIC_BACKEND_WS_URL
            value: "ws://central-backend.{{ .Release.Namespace }}.svc.cluster.local:8081/graphql"
          resources:
            requests:
              cpu: {{ .Values.centralUI.resources.requests.cpu }}
              memory: {{ .Values.centralUI.resources.requests.memory }}
            limits:
              cpu: {{ .Values.centralUI.resources.limits.cpu }}
              memory: {{ .Values.centralUI.resources.limits.memory }}
      {{- with .Values.centralUI.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.centralUI.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.centralUI.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
