package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"
	"time"

	"github.com/odigos-io/odigos/frontend/graph/model"
)

// GetServiceMap is the resolver for the getServiceMap field.
func (r *queryResolver) GetServiceMap(ctx context.Context) (*model.ServiceMap, error) {
	if r.MetricsConsumer == nil {
		return nil, fmt.Errorf("metrics consumer not initialized")
	}

	serviceMap := r.MetricsConsumer.GetServiceGraphEdges()
	services := make([]*model.ServiceMapFromSource, 0)

	for serviceName, toServices := range serviceMap {
		to := make([]*model.ServiceMapToSource, 0)

		for toServiceName, info := range toServices {
			to = append(to, &model.ServiceMapToSource{
				ServiceName: toServiceName,
				Requests:    int(info.RequestCount),
				DateTime:    info.LastUpdated.Format(time.RFC3339),
			})
		}

		services = append(services, &model.ServiceMapFromSource{
			ServiceName: serviceName,
			Services:    to,
		})
	}

	return &model.ServiceMap{Services: services}, nil
}
