{{- if (include "odigos.secretExists" .) }}
{{- if .Values.keycloak.enabled }}
{{- if not .Values.keycloak.adminPassword }}
{{- fail "Keycloak admin password is required. Please use --set keycloak.adminPassword=<your-password>" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
type: Opaque
data:
  admin-username: {{ .Values.keycloak.adminUsername | b64enc }}
  admin-password: {{ .Values.keycloak.adminPassword | b64enc }}
{{- end }}
{{- end }} 