{{- if and .Values.centralBackend.enabled .Values.centralBackend.token }}
apiVersion: v1
kind: Secret
metadata:
  name: odigos-central
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ODIGOS_ONPREM_TOKEN: {{ .Values.centralBackend.token | quote }}
{{- end }}
